### PR TITLE
I would like to add a Meteor subscribe to the boiler plate

### PR DESCRIPTION
**Pull request by PolGuixe**
This is simple example how to subscribe to a collection and display some information. 

If you think that it needs to be more completed we can work on it. 

Looking for your feedback.

### CODE REVIEW

**Comment by PolGuixe** [comment]
Here you can see what it does: 

http://recordit.co/T6h4oQec7g

**Comment by Jarskih** [comment]
I tried this and got this error: 

```
error][tid:com.facebook.react.JavaScript] { [Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Details`.]
  line: 10433,
  column: 16,
  sourceURL: 'http://192.168.1.112:8081/index.ios.bundle?platform=ios&dev=true',
  name: 'Invariant Violation',
  framesToPop: 1 }
```

**Comment by Jarskih** [comment]
I solved it by using MeteorComplexListView. For some reason the MeteorListView does not work. Might be issue with react-native-meteor.

**Comment by spencercarli** [comment]
Thanks for opening this! I'm in the middle of a move but will try to check this out soon

**Comment by spencercarli** [comment]
Geez just realized this was from nearly a month ago. My apologies for not checking it out sooner - slipped through the cracks!

**Comment by PolGuixe** [comment]
No worries. Can we check if the code if up to date and merge it?

**Comment by spencercarli** [comment]
Could you remove `meteortoys:allthings` from `MeteorApp` and `.jshintrc` from `RNApp`?

**Comment by PolGuixe** [comment]
@spencercarli done ;)

**Comment by spencercarli** [comment]
Hmm looks like meteortoys is still in `MeteorApp/.meteor/versions`

**Comment by PolGuixe** [comment]
upsss...,sorry. 

Fixed.

**Comment by spencercarli** [comment]
Thanks @PolGuixe!

**Pull request merged**
